[package]
name = "heorot"
description = "A very simple Rust-based OS"
version = "0.1.0"
edition = "2018"
authors = "Scott Reu"
license = "MIT"
license_file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
